name: inventory

services:
  app:
    image: snipe/snipe-it:v8.0.4
    pull_policy: if_not_present
    container_name: inventory-web
    restart: unless-stopped
    volumes:
      - storage:/var/lib/snipeit
    ports:
      - "${APP_PORT}:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mariadb:11.5.2
    pull_policy: if_not_present
    container_name: inventory-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 1s
      retries: 5

volumes:
  db_data:
  storage:
